// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfChF-vVZYmfMYXb5N6A_bdjY2NwuZAPs',
    appId: '1:588949939914:web:4fcedc00618bd05ae37633',
    messagingSenderId: '588949939914',
    projectId: 'safestride-c260f',
    authDomain: 'safestride-c260f.firebaseapp.com',
    storageBucket: 'safestride-c260f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMicfDlyBACIMzeRpZt9xtsGEopPUsq0',
    appId: '1:588949939914:android:bb44aeee9d88ffade37633',
    messagingSenderId: '588949939914',
    projectId: 'safestride-c260f',
    storageBucket: 'safestride-c260f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjykrhzfBVoMI9rJGngYPVmQT0EWMaZQ',
    appId: '1:588949939914:ios:aebf8d5c816b6936e37633',
    messagingSenderId: '588949939914',
    projectId: 'safestride-c260f',
    storageBucket: 'safestride-c260f.firebasestorage.app',
    iosBundleId: 'com.example.safestride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSjykrhzfBVoMI9rJGngYPVmQT0EWMaZQ',
    appId: '1:588949939914:ios:aebf8d5c816b6936e37633',
    messagingSenderId: '588949939914',
    projectId: 'safestride-c260f',
    storageBucket: 'safestride-c260f.firebasestorage.app',
    iosBundleId: 'com.example.safestride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfChF-vVZYmfMYXb5N6A_bdjY2NwuZAPs',
    appId: '1:588949939914:web:c81a620c45f88a3fe37633',
    messagingSenderId: '588949939914',
    projectId: 'safestride-c260f',
    authDomain: 'safestride-c260f.firebaseapp.com',
    storageBucket: 'safestride-c260f.firebasestorage.app',
  );
}
